# This file is REQUIRED for the server to recognize and load our plugin.
name: Trailblazer
version: 1.0.0 # This will be automatically replaced by the version in build.gradle
main: com.trailblazer.plugin.TrailblazerPlugin # The main class of our plugin (we will create this next)
api-version: '1.21.8'
author: Mod MC
description: Server-side Path Sharing plugin authoritative path persistence, sharing, and server-render fallback for unmodded clients; integrates with the Fabric client for full client/server UX.
# --- ADD THIS ENTIRE BLOCK ---
commands:
  trailblazer:
    description: "Unified Path-Sharing command (preferred). Subcommands: view, hide, delete, rename, share, rendermode, color, info, record"
    usage: /<command> [subcommand]
  tbl:
    description: "Alias for /trailblazer"
    usage: /<command> [subcommand]
# --- END ADDITION ---